version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
